### ISSUE TITLE
forceReload is not passed on to loadSpikes

### ISSUE THREAD

**Issue by SaraMati** [petersenpeter/CellExplorer#10]
at the moment, setting the forceReload to True in ProcessCellMetrics is not passed on to the loadSpikes function. 
when in fact, I need to read the spikes from the Phy results again, because I have changed the manual clustering (e.g. merged or removed a noisy cluster)

by using this command: ProcessCellMetrics('session', session, 'forceReload',true);
the forceReload parameter value is not passed on to loadSpikes and hence in line 66 the parameter is set to false. 
and the conditional statement in line 108 is not True because all the required fields exist. so it doesn't assume "spikes.mat not up to data" and reloads the existing spikes. 

is there a separate parameter that I should define for it? or perhaps a fix is required.

**Comment by petersenpeter** [comment]
Hi Sara

We can change this. The current logic (which is not always consistent perhaps) is that other files are not overwritten even with forceReload. In this case, the spikes struct will not be overwritten. Now, every calculation will be redone with forceReload.
