### ISSUE TITLE
Unrecognized function or variable 'ydata'

### ISSUE THREAD

**Issue by CWarrick** [petersenpeter/CellExplorer#101]
Hello, my name is Collin, I'm a grad student at Johns Hopkins. I've just started working with CellExplorer and have run into an issue regarding ACG fit. While running CellMetrics, MatLab returned this error while fitting the triple exponential:
<img width="1904" alt="Screenshot 2023-11-05 at 1 07 25 AM" src="https://github.com/petersenpeter/CellExplorer/assets/45715062/61e1e1c6-73d6-4835-b12c-765e0b60cca6">
It seems like there is not a 'ydata' variable defined prior to line 75 in fit_ACG as needed here:
https://github.com/petersenpeter/CellExplorer/blob/31562ecb347f6c83b4f7c6bb575effafec5b56ce/calc_CellMetrics/fit_ACG.m#L75
There is a 'ydata' in a subsequent section of fit_ACG entitled "Optimization Toolbox", however the lines are inactive, so I'm unsure if they are meant to resolve this or not.
My data is from a Neuropixels recording, processed with KiloSort and output from Phy. I collaborated with another scientist to gather this data who has a much better knowledge of Neuropixels than I do, so if there is more information required, I will have to reach out to them. If anyone can provide some guidance on this topic, it would be greatly appreciated, thank you!

**Comment by petersenpeter** [comment]
Hi Warrick 

I pushed a fix for this. Please update your repo and try again. 

Let me know if this fixes your issue.
