### ISSUE TITLE
Request for CCGHeart.mexmaca64 

### ISSUE THREAD

**Issue by RunjieTomYi** [petersenpeter/CellExplorer#102]
Hi Peter,
I was trying to compile mex on my mac and XCode 15(the only version MacOS14 can open) is not supported by MATLAB. So running the mex line generates following error. 
I'm wondering if it's possible for you to compile a CCGHeart with mexmaca64 format. Any other possible solutions are appreciated.

**Operating system**
MacOS Sonoma 14.0

**Matlab version**
R2023b

**Matlab error log**
Building with 'Xcode with Clang'.
Error using mex
/Users/tomyi/Research/CellExplorer-master/calc_CellMetrics/mex/CCGHeart.c:195:3: error: call to undeclared library function
'memcpy' with type 'void *(void *, const void *, unsigned long)'; ISO C99 and later do not support implicit function
declarations [-Wimplicit-function-declaration]
                memcpy(mxGetPr(plhs[1]), (void *)Pairs, PairCnt*sizeof(unsigned int));
                ^
/Users/tomyi/Research/CellExplorer-master/calc_CellMetrics/mex/CCGHeart.c:195:3: note: include the header <string.h> or
explicitly provide a declaration for 'memcpy'
1 error generated.
 
**Screenshots**
<img width="1198" alt="Screenshot 2023-12-08 at 16 40 45" src="https://github.com/petersenpeter/CellExplorer/assets/64788721/25efaaf1-837c-46c6-8757-5308069bae05">

**Comment by petersenpeter** [comment]
Hi 

I updated the repository with a compiled version for Apple Silicon (CCGHeart.mexmaca64 and FindInInterval.mexmaca64). Could you test and see if this works for you?

**Comment by RunjieTomYi** [comment]
It's working fine now. Much thanks!
