### ISSUE TITLE
db_is_active not found

### ISSUE THREAD

**Issue by evilrobotxoxo** [petersenpeter/CellExplorer#112]
**Operating system**
MacOS Sonoma 14.5

**Matlab version**
R2024a

**Describe the bug**
When I try to load a .dat file, I get an error saying: 

Unrecognized function or variable 'db_is_active'.
Error in => NeuroScope2.m at line 96

**Matlab setpath**
A common problem is interferences with other toolboxes. If possible, please provide your search path by typing `path` in Matlab.

/Users/lukesjulson/Documents/MATLAB
	/Users/lukesjulson/Desktop/github/buzcode
	/Users/lukesjulson/Desktop/github/buzcode/GUITools
	/Users/lukesjulson/Desktop/github/buzcode/GUITools/EventExplorer
	/Users/lukesjulson/Desktop/github/buzcode/GUITools/EventExplorer/EEhelpers
	/Users/lukesjulson/Desktop/github/buzcode/GUITools/TheStateEditor
	/Users/lukesjulson/Desktop/github/buzcode/analysis
	/Users/lukesjulson/Desktop/github/buzcode/analysis/CrossFrequencyCoupling
	/Users/lukesjulson/Desktop/github/buzcode/analysis/RankOrder
	/Users/lukesjulson/Desktop/github/buzcode/analysis/SharpWaveRipples
	/Users/lukesjulson/Desktop/github/buzcode/analysis/SharpWaveRipples/detect_swr
	/Users/lukesjulson/Desktop/github/buzcode/analysis/SpectralAnalyses
	/Users/lukesjulson/Desktop/github/buzcode/analysis/assemblies
	/Users/lukesjulson/Desktop/github/buzcode/analysis/cellTypeClassification
	/Users/lukesjulson/Desktop/github/buzcode/analysis/cellTypeClassification/BrendonClassificationFromStark2013
	/Users/lukesjulson/Desktop/github/buzcode/analysis/lfp_general
	/Users/lukesjulson/Desktop/github/buzcode/analysis/monosynapticPairs
	/Users/lukesjulson/Desktop/github/buzcode/analysis/monosynapticPairs/utils
	/Users/lukesjulson/Desktop/github/buzcode/analysis/placeFields
	/Users/lukesjulson/Desktop/github/buzcode/analysis/positionDecoding
	/Users/lukesjulson/Desktop/github/buzcode/analysis/spikeLFPcoupling
	/Users/lukesjulson/Desktop/github/buzcode/analysis/spikes
	/Users/lukesjulson/Desktop/github/buzcode/analysis/spikes/correlation
	/Users/lukesjulson/Desktop/github/buzcode/analysis/spikes_general
	/Users/lukesjulson/Desktop/github/buzcode/analysis/spikes_general/InterSpikeIntervals
	/Users/lukesjulson/Desktop/github/buzcode/database
	/Users/lukesjulson/Desktop/github/buzcode/detectors
	/Users/lukesjulson/Desktop/github/buzcode/detectors/detectBehavior
	/Users/lukesjulson/Desktop/github/buzcode/detectors/detectBehavior/detect_pupilDilation
	/Users/lukesjulson/Desktop/github/buzcode/detectors/detectBehavior/detect_vocalizations
	/Users/lukesjulson/Desktop/github/buzcode/detectors/detectBehavior/detect_whisking
	/Users/lukesjulson/Desktop/github/buzcode/detectors/detectEvents
	/Users/lukesjulson/Desktop/github/buzcode/detectors/detectStates
	/Users/lukesjulson/Desktop/github/buzcode/detectors/detectStates/SleepScoreMaster
	/Users/lukesjulson/Desktop/github/buzcode/detectors/detectStates/SleepScoreMaster/ScoringParameters
	/Users/lukesjulson/Desktop/github/buzcode/detectors/detectStates/SleepScoreMaster/StateScoreFigures
	/Users/lukesjulson/Desktop/github/buzcode/detectors/detectStates/SleepScoreMaster/TestsAndExamples
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/CONVNFFT
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/CircularStats
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/CircularStats/examples
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/ExportFig
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/FMAToolbox
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/FMAToolbox/Analyses
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/FMAToolbox/Data
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/FMAToolbox/Database
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/FMAToolbox/General
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/FMAToolbox/Helpers
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/FMAToolbox/IO
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/FMAToolbox/Plot
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/FilterM
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/IoSR-Surrey-MatlabToolbox-4bff1bb
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/IoSR-Surrey-MatlabToolbox-4bff1bb/deps
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/IoSR-Surrey-MatlabToolbox-4bff1bb/deps/SOFA_API
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/IoSR-Surrey-MatlabToolbox-4bff1bb/deps/SOFA_API/conventions
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/IoSR-Surrey-MatlabToolbox-4bff1bb/deps/SOFA_API/converters
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/IoSR-Surrey-MatlabToolbox-4bff1bb/deps/SOFA_API/coordinates
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/IoSR-Surrey-MatlabToolbox-4bff1bb/deps/SOFA_API/demos
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/IoSR-Surrey-MatlabToolbox-4bff1bb/deps/SOFA_API/helper
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/IoSR-Surrey-MatlabToolbox-4bff1bb/deps/SOFA_API/netcdf
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/IoSR-Surrey-MatlabToolbox-4bff1bb/deps/SOFA_API/test
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/LopesdosSantos_AssemblyToolbox
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/LopesdosSantos_AssemblyToolbox/examples
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/WaveletToolbox
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/WaveletToolbox/example
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/arfit
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/dataio
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/dataio/HowToReadNexFilesInMatlab
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/dataio
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/dataio/HowToReadNexFilesInMatlab
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/dataio/ReadingPLXandDDTfilesinMatlab
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/fly_track
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/fly_track/FAnalyze
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/fly_track/FAnalyze/functions
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/fly_track/FTrack
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/fly_track/FTrack/functions
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/fly_track/videoIO
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/fly_track/videoIO/videoIO_2006a
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/fly_track/videoIO/videoIO_2006b
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/fly_track/videoIO/videoIO_2007a
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/locfit
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/locfit/Book
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/locfit/Neuro
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/locfit/m
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/old
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/old/tutorial
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/spectral_analysis
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/spectral_analysis/continuous
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/spectral_analysis/helper
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/spectral_analysis/hybrid
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/spectral_analysis/plots
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/spectral_analysis/pointbinned
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/spectral_analysis/pointtimes
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/spectral_analysis/specscope
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/spectral_analysis/statistical_tests
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/test
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/documentation/chronux_2_10/wave_browser
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/fly_track
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/fly_track/FAnalyze
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/fly_track/FAnalyze/documentation
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/fly_track/FAnalyze/documentation/TeXFiles
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/fly_track/FAnalyze/functions
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/fly_track/FTrack
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/fly_track/FTrack/documentation
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/fly_track/FTrack/documentation/TeXFiles
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/fly_track/FTrack/functions
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/fly_track/videoIO
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/fly_track/videoIO/videoIO_2006a
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/fly_track/videoIO/videoIO_2006b
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/fly_track/videoIO/videoIO_2007a
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/locfit
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/locfit/Book
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/locfit/Neuro
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/locfit/Source
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/locfit/m
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/locfit/mex
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/locfit/mex/dll
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/old
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/old/tutorial
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/spectral_analysis
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/spectral_analysis/continuous
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/spectral_analysis/helper
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/spectral_analysis/hybrid
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/spectral_analysis/plots
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/spectral_analysis/pointbinned
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/spectral_analysis/pointtimes
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/spectral_analysis/specscope
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/spectral_analysis/statistical_tests
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/test
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/wave_browser
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/chronux_2_12/wave_browser/html
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/external
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/functions
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/functions/adminfunc
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/functions/guifunc
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/functions/javachatfunc
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/functions/miscfunc
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/functions/popfunc
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/functions/sigprocfunc
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/functions/statistics
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/functions/studyfunc
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/functions/timefreqfunc
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/plugins
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/plugins/dipfit2.3
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/elec
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/skin
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BESA
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/plugins/firfilt1.6.2
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/sample_data
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/eeglab14_0_0b/sample_locs
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/fastBSpline
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/ndt_1_0_4
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/ndt_1_0_4/Zhang_Desimone_7objects_raster_data
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/ndt_1_0_4/classifiers
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/ndt_1_0_4/cross_validators
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/ndt_1_0_4/datasources
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/ndt_1_0_4/feature_preprocessors
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/ndt_1_0_4/helper_functions
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/ndt_1_0_4/position_invariance_results
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/ndt_1_0_4/tools
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/ndt_1_0_4/tutorials
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/npy-matlab-master
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/npy-matlab-master/npy-matlab-master
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/npy-matlab-master/npy-matlab-master/.ipynb_checkpoints
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/npy-matlab-master/npy-matlab-master/data
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/parfor_progress
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/plexonSDK
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/plexonSDK/Samples
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/plexonSDK/mexPlex
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/plexonSDK/mexPlex/tests
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/structdlg
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/structdlg/structdlg
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/structdlg/structdlg/ref
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/tSNE_matlab
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/v2struct_2011_09_12
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/v2struct_2011_09_12/html
	/Users/lukesjulson/Desktop/github/buzcode/externalPackages/xmltree-2.0
	/Users/lukesjulson/Desktop/github/buzcode/generalComputation
	/Users/lukesjulson/Desktop/github/buzcode/generalComputation/probox_RAID_setup_instructions
	/Users/lukesjulson/Desktop/github/buzcode/io
	/Users/lukesjulson/Desktop/github/buzcode/preprocessing
	/Users/lukesjulson/Desktop/github/buzcode/preprocessing/amplipexToolbox
	/Users/lukesjulson/Desktop/github/buzcode/preprocessing/autoClustering
	/Users/lukesjulson/Desktop/github/buzcode/preprocessing/intanToolbox
	/Users/lukesjulson/Desktop/github/buzcode/preprocessing/metadata
	/Users/lukesjulson/Desktop/github/buzcode/preprocessing/metadata/BWMetadataSystem
	/Users/lukesjulson/Desktop/github/buzcode/preprocessing/old
	/Users/lukesjulson/Desktop/github/buzcode/preprocessing/positionTracking
	/Users/lukesjulson/Desktop/github/buzcode/preprocessing/positionTracking/LEDTracking
	/Users/lukesjulson/Desktop/github/buzcode/preprocessing/positionTracking/Spotter
	/Users/lukesjulson/Desktop/github/buzcode/preprocessing/positionTracking/optitrack
	/Users/lukesjulson/Desktop/github/buzcode/preprocessing/probeGeometries
	/Users/lukesjulson/Desktop/github/buzcode/preprocessing/ratemapping
	/Users/lukesjulson/Desktop/github/buzcode/preprocessing/sessionsManagement
	/Users/lukesjulson/Desktop/github/buzcode/preprocessing/signalAlignment
	/Users/lukesjulson/Desktop/github/buzcode/tutorials
	/Users/lukesjulson/Desktop/github/buzcode/tutorials/exampleDataStructs
	/Users/lukesjulson/Desktop/github/buzcode/tutorials/exampleDataStructs/20170505_396um_0um_merge
	/Users/lukesjulson/Desktop/github/buzcode/utilities
	/Users/lukesjulson/Desktop/github/buzcode/utilities/fileConversions
	/Users/lukesjulson/Desktop/github/buzcode/utilities/fileConversions/ConvertToPlexon
	/Users/lukesjulson/Desktop/github/buzcode/utilities/fileConversions/LinuxBasedPCAForFets
	/Users/lukesjulson/Desktop/github/buzcode/visualization
	/Users/lukesjulson/Desktop/github/buzcode/visualization/colormaps
	/Users/lukesjulson/Desktop/github/buzcode/visualization/colormaps/ColorPaletteGenerators
	/Users/lukesjulson/Desktop/github/buzcode/visualization/colormaps/crameri
	/Users/lukesjulson/Desktop/github/buzcode/visualization/colormaps/crameri/html
	/Users/lukesjulson/Desktop/github/buzcode/visualization/colormaps/makeColorMap

**Comment by petersenpeter** [comment]
Hi Luke

It seems you did not add the CellExplorer subfolders to the Matlab path (you can exclude the folder docs and its subfolders). Go to "Set Path" from the top menu, click the button "Add with subfolders...", and select your CellExplorer folder.

I would also recommend having the CellExplorer folders above your buzcode folders in the set path. 

Let me know how it goes. Happy to chat on zoom as well.

**Comment by evilrobotxoxo** [comment]
I see, that's kind of obvious in retrospect. Thanks!

**Comment by petersenpeter** [comment]
Happy to help. Let me know if you still experience any issues.

**Comment by evilrobotxoxo** [comment]
Thanks, and sorry to bother you with something so silly - it didn’t occur
to me that I needed to set a path for the compiled version. Hope all is
well!
