### ISSUE TITLE
No NPX 2.0 compatibility?

### ISSUE THREAD

**Issue by taningh86** [petersenpeter/CellExplorer#114]
Hi,
Sorry, for posting it also here in issues (I posted in discussions too). Hope that's ok. I have just started to use cellExplorer and trying to figure things out. I am assuming I will have more questions in the future and I hope that's ok. Will very much appreciate your help in this process.
The first question I have for now is if 4-shank neuropixels probe is supported in CellExplorer? I only see IMEC NPX 1.0. But if it is possible somehow then how to add the electrode groups. Is there a guide to it? I am not seeing in the documentations. Please let me know.

Thanks
Jimmy

**Operating system**
Windows 10

**Matlab version**
2023b

**Describe the bug**

**Matlab error log**
Unrecognized field name "electrodeGroups".

Error in ProcessCellMetrics (line 219)
if any([session.extracellular.electrodeGroups.channels{:}]==0)

**Session struct**
If relevant, please provide your session Matlab struct (`basename.session.mat`) by zipping it and dragging it into this text field. This will ease the troubleshooting. 

**Screenshots**

**Additional context**

**Matlab setpath**
A common problem is interferences with other toolboxes. If possible, please provide your search path by typing `path` in Matlab.

**Comment by petersenpeter** [comment]
Hi 

Please see my reply in the discussion: https://github.com/petersenpeter/CellExplorer/discussions/113

**Comment by petersenpeter** [comment]
I am closing this issue, but we can continue in the discussion section.
