### ISSUE TITLE
Will mountainsort be supported? 

### ISSUE THREAD

**Issue by ajcheng1** [petersenpeter/CellExplorer#119]
I read in the paper that Mountainsort is supported but under loadSpikes.m it says "mountainsort output format not implemented yet"

**Comment by ajcheng1** [comment]
Gotcha. My mountainsort data is unconventionally from preprocessed converted data from numpy, but happy to share. I was able to export it to Phy and then upload it to CellExplorer, but the filtered waveform graph is not showing the individual spikes accurately. Let me know how I can best send you the data (~a couple of gb)

**Comment by petersenpeter** [comment]
If you have it in the phy format, you can easily import it into CellExplorer. Could you elaborate on the issue with the filtered waveforms? 

I cannot host the data, so you must find a way to share it.

**Comment by ajcheng1** [comment]
Actually nvm about that! I realized I was looking at single waveform and not waveforms (all). 
Slightly related question, given I used mountainsort for spike sorting, my raw data is from numpy. Is it possible for CellExplorer to read .npy files as the raw data instead of .dat?

**Comment by petersenpeter** [comment]
Yes, but it doesn't currently support it. I am not sure it is wise to use numpy instead of a binary format, though.
