### ISSUE TITLE
[Help!] ACG_tau_rise

### ISSUE THREAD

**Issue by Lorena-J** [petersenpeter/CellExplorer#120]
Hi!! I'm trying to understand how you calculate ACG_tau_rise but I can't figure it out. Could you please explain to me how you do the calculation? 
Thank you very much!!

**Comment by petersenpeter** [comment]
Hi. You can find a description here: https://cellexplorer.org/pipeline/acg-fit/

**Comment by petersenpeter** [comment]
Feel free to reopen the issue!
