### ISSUE TITLE
add the interval name tag to the name of the summary figure for saving 

### ISSUE THREAD

**Issue by SaraMati** [petersenpeter/CellExplorer#18]
when cell_metrics is run for several intervals, only the last summary figure is saved because the name under which those figures are saved is the same. i.e. the name tag of the interval is not carried over to the name under which the summary figure is saved. 
not urgent, but useful to save the summary figures with distinct names

**Comment by petersenpeter** [comment]
Hi Sara

Thanks for this. I pushed an update to GitHub adding the name of the metrics (e.g cell_metrics) to the files and figures.
