### ISSUE TITLE
Cells possibly classified incorrectly, and weird monosynaptic connections

### ISSUE THREAD

**Issue by KaiserArndt2** [petersenpeter/CellExplorer#25]
Hey Peter,

The image below has a cell with an ACG that looks like a pyramidal cell but is classified as a narrow interneuron. The monosynaptic connections also show a lot of classified interneurons giving excitatory input to other cells.  Not sure if it helps, but this recording is from the retrosplenial cortex.

![image](https://user-images.githubusercontent.com/46385650/110175838-640a5380-7dd0-11eb-9333-8d0766f5ccbe.png)

**Comment by petersenpeter** [comment]
Hi 

I never worked with data from the retrosplenial cortex, but a narrow waveform bursting cell, as in your example, is something I have not seen in data from the visual cortex or the hippocampus. Could it perhaps be an issue with the spike sorting, where a pyramidal cell was grouping with an interneuron? Narrow waveform neurons are almost exclusively inhibitory from my experience. See this page for the classification: https://cellexplorer.org/pipeline/cell-type-classification/
The fraction of wide waveform interneurons in your data is too high, so many of these are likely pyramidal cells. If you share the cell_metrics file with me I can take a look at it. The thresholds used for the cell type classification are verified with visual cortex and hippocampal data, but for other brain regions, I cannot say how well it will perform. If you are willing to share a set of retrosplenial cortex datasets with me, I can take a look at this. 

Did you manually curate the monosynaptic connections? I strongly suggest this. Use the GUI for this: https://cellexplorer.org/tutorials/monosynaptic-connections-tutorial/#manual-curation
