### ISSUE TITLE
getBasenameFromDir is missing

### ISSUE THREAD

**Issue by SaraMati** [petersenpeter/CellExplorer#28]
'getBasenameFromDir' which is called in 'basenameFromBasepath' is missing from the repo

**Comment by petersenpeter** [comment]
hmm, this is odd, it is a function embedded in basenameFromBasepath.

**Comment by petersenpeter** [comment]
I removed the embedded function and cleaned up the code. Could you try again?

**Comment by petersenpeter** [comment]
Hey Sara

I am closing the issue now. Let me know if you still have issues.
