### ISSUE TITLE
Running CellExplorer with Example Data Error

### ISSUE THREAD

**Issue by AJPerez-Ignacio** [petersenpeter/CellExplorer#41]
Hi there,

I have successfully downloaded CellExplorer and am trying to run CellExplorer with the provided example data (cell_metrics_batch.mat) that comes with the installation, however I am running into an error. I am following the instructions on the 'Getting Started' page of CellExplorer but run into the following error message:

Attempt to execute SCRIPT CellExplorer as a function:
C:\Users\User\Documents\AJ\Data\MATLAB-20210304T193031Z-001\MATLAB\CellExplorer.m

Error in CellExplorer (line 10)
CellExplorer('metrics',cell_metrics)

I have added the appropriate path and I am running R2020 version of MATLAB, windows 64-bit.  Is there something I am missing?

**Comment by petersenpeter** [comment]
Hi 

That command should work, could you try to reboot Matlab or your computer? I have seen this behavior very few times myself but a reboot should fix it. 

Otherwise, could you run this command for me? 
`which CellExplorer -all`

**Comment by petersenpeter** [comment]
I am closing this issue now, but feel free to reopen if you still experience any issues.
