### ISSUE TITLE
Problems running mex -O CCGHeart.c

### ISSUE THREAD

**Issue by farazmoradi** [petersenpeter/CellExplorer#47]
Hi Peter, 

I have received this error while installing the toolbox. I have installed Xcode which has a c compiler by default. 

**Operating system**
Mac

**Matlab version**
2021B

**Describe the bug**
Error using mex
/Volumes/Projects/CellExplorer-master/calc_CellMetrics/mex/CCGHeart.c:195:3: error: implicitly declaring library function 'memcpy'
with type 'void *(void *, const void *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
                memcpy(mxGetPr(plhs[1]), (void *)Pairs, PairCnt*sizeof(unsigned int));
                ^
/Volumes/Projects/CellExplorer-master/calc_CellMetrics/mex/CCGHeart.c:195:3: note: include the header <string.h> or explicitly
provide a declaration for 'memcpy'
1 error generated.

**Comment by petersenpeter** [comment]
Hi Faraz

I am closing this issue as it has been fixed per mail. 

**Solution**
The c-code functions has to be compiled:
https://cellexplorer.org/#getting-started
