### ISSUE TITLE
conflict between Kilosort3 and CellExplorer

### ISSUE THREAD

**Issue by DaniMagyar** [petersenpeter/CellExplorer#56]
Hi, 

Unfortunately Kilosort GUI does not work when CellExplorer is added to Matlab path. When I try to run Kilosort3 in Matlab, I get the following error:

```
>> kilosort
Error using uiextras.Panel
Cannot define property 'Enable' in class 'uiextras.Panel' because the
property has already been defined in the superclass
'matlab.ui.container.Panel'.

Error in ksGUI/build (line 112)
            obj.H.logPanel = uiextras.Panel(...

Error in ksGUI (line 47)
            obj.build(parent);

Error in kilosort (line 18)
h = ksGUI(f);
```

```
>> which uiextras.Panel
C:\Users\dmagyar\Documents\Matlab_toolboxes_DM\CellExplorer\toolboxes\GUI Layout Toolbox 2.3.4\layout\+uiextras\Panel.m  % uiextras.Panel constructor
```

I have to remove CellExplorer from the path every time I use Kilosort3. Do you have any suggestions how to solve this problem?

Thank you,
Daniel

**Comment by petersenpeter** [comment]
Hi Daniel 

I believe it is because we use different versions of the same GUI toolbox (GUI Layout Toolbox). 

https://se.mathworks.com/matlabcentral/fileexchange/47982-gui-layout-toolbox

The GUI Layout Toolbox version 2.3.4 is included with CellExplorer, but Kilosort might use a different version? Could you check which version you have installed with KiloSort?

- Peter

**Comment by DaniMagyar** [comment]
Thanks for the quick response. I have the 2.3.5 version.

**Comment by petersenpeter** [comment]
OK, I will update CellExplorer to use the same version 2.3.5 (the most recent version) of the toolbox then. This should solve the issue. Hopefully by tomorrow.

**Comment by DaniMagyar** [comment]
I have tried different versions in the meantime. It seems like Kilosort3 GUI does not work with GUI Layout Toolbox v2.3.4. Thank you for your help.

**Comment by petersenpeter** [comment]
Hi Daniel, I updated the CellExplorer repo where I removed GUI Layout Toolbox v2.3.4 and included GUI Layout Toolbox v2.3.5. You will have to update your Matlab set path. Let me know if this fixes your issues.

**Comment by DaniMagyar** [comment]
Hi Peter, the update solved the problem, both Kilosort and CellExplorer work perfectly. Thanks!

**Comment by petersenpeter** [comment]
Great. I will close the issue but feel free to open it if you experience further issues.
