### ISSUE TITLE
Generalization for all sampling frequencies

### ISSUE THREAD

**Issue by hyr2** [petersenpeter/CellExplorer#57]
**Is your feature request related to a problem? Please describe.**
The script CCG.m assumes a default value of 20KHz for the sampling rate. Many labs record at 25KHz or 30KHz. This needs to be generalized. To generalize it, we need to add an extra input parameter for the function that calls CCG.m: ce_MonoSynConvClick.m

**Describe the solution you'd like**
I am attaching the updated ce_MonoSynConvClick.m so that you can make the appropriate change. I have added an extra input parameter for the sampling rate.  
![Screenshot from 2022-04-18 19-12-33](https://user-images.githubusercontent.com/51006894/163896082-a44467ad-497f-4fa0-a306-466facd31ea3.png)
![Screenshot from 2022-04-18 19-12-08](https://user-images.githubusercontent.com/51006894/163896086-30eb9248-9044-4fa2-b91f-4dba6f3e5822.png)

**Comment by petersenpeter** [comment]
Hi 

Thanks for the suggestion and code. I incorporated the changes across the various CCG calls, as you suggested, but maintained the variable name `sr` for sampling rate. For historical reasons, the CCG function takes `Fs=1/sr` as input. 

Here is the commit:
https://github.com/petersenpeter/CellExplorer/commit/69c4a1eca9aba5ec8dc6eaee6f75fdc96c7d283e

**Comment by petersenpeter** [comment]
I am closing this issue now, but feel free to open it if you still experience issues.
