### ISSUE TITLE
Saving cellMetrics to nwb

### ISSUE THREAD

**Issue by PatrickHonma** [petersenpeter/CellExplorer#64]
Hi Peter,

Thank you for this awesome tool; it's working great so far! 

When trying to save my cellMetrics to nwb with saveCellMetrics2nwb, I encounter this error:
Unrecognized function or variable 'generateExtension'.

I can't seem to find this function in the repo or embedded in saveCellMetrics2nwb.

Thanks,
Patrick

**Comment by petersenpeter** [comment]
Hi Patrick

I believe you are missing the matnwb toolset:
https://github.com/NeurodataWithoutBorders/matnwb

Add it to your Matlab path, try again, and then let me know if you experience further issues.

/ Peter

**Comment by petersenpeter** [comment]
Great Patrick. 

I added the dependency/requirement of the matnwb toolset to the nwb tutorials.
