### ISSUE TITLE
Putative cell classification criteria

### ISSUE THREAD

**Issue by ruxyb2004k** [petersenpeter/CellExplorer#7]
Hi Peter,

first of all, thank you for this amazing tool and all the effort you put into it and for sharing it with the community.
As I was going through the tutorials and explanations, I fount one contradiction regarding how the cells were classified in the section datastructure/standard-cell-metrics/ , more precisely regarding narrow vs wide interneurons. I guess all interneurons are classified without any restriction on the trough to peak time, then they are split into the two classes based on this criterion. It would be great if this was clarified on the website.
Thanks in advance and keep up the good work.

Greetings,
Ruxandra

**Comment by petersenpeter** [comment]
Hi Ruxandra

Thanks for your interest in CellExplorer. As far as I can see from the [documentation](https://cellexplorer.org/datastructure/standard-cell-metrics/#cell-type-classification) and the actual [code](https://github.com/petersenpeter/CellExplorer/blob/master/ProcessCellMetrics.m#L1252), there is no discrepancy between them. It is true that a narrow waveform spike will always be classified as interneurons first. If there is a discrepancy somewhere else, please let me know. 

Best regards,
Peter

**From the documentation:**
Putative cell types:
In the processing pipeline, cells are classified into three putative cell types: Narrow Interneurons, Wide Interneurons and Pyramidal Cells.
Interneurons are selected by 3 separate criteria:
1. acg_tau_decay > 30 ms
2. acg_tau_rise > 3 ms
3. troughToPeak <= 0.425 ms

Next interneurons are separated into two classes
- Narrow interneuron assigned if troughToPeak <= 0.425 ms
- Wide interneuron assigned if troughToPeak > 0.425 ms

Remaining cells are assigned as Pyramidal cells.

**Comment by ruxyb2004k** [comment]
Hi Peter,

thanks for your reply. Now I understood the documentation by looking at the code. In the beginning, I thought an interneuron has to meet all 3 criteria (AND), but now I understood that it can meet any of the 3 criteria (OR).

Best wishes,
Ruxandra
