### ISSUE TITLE
Mismatch between size of detection of connections and transmission probability matrix

### ISSUE THREAD

**Issue by rajatsaxena** [petersenpeter/CellExplorer#75]
**Operating system**
Ubuntu 18.04

**Matlab version**
2019a

**Describe the bug**
There is a mismatch between size of `cell_metrics.excitatory` and `cell_metrics.excitatoryTransProb` variables.

**Screenshots**
![1](https://user-images.githubusercontent.com/5181888/196001494-a90ef5f8-5fa1-48de-a8e3-4b59db8c9ecb.png)

**Comment by petersenpeter** [comment]
Hi. I am not able to reproduce this issue. Could you share your dataset with me?

**Comment by rajatsaxena** [comment]
It was a matter of running the scripts in some asynchronous way, just rerunning the whole thing took care of it. Thanks!
