### ISSUE TITLE
Behavioral trials not yet supported

### ISSUE THREAD

**Issue by Jialiang-Lu** [petersenpeter/CellExplorer#83]
Hi! When testing your powerful toolkit with your example dataset, I noticed that computations regarding behavioral trials are not yet implemented. The file Peter_MS22_180629_110319_concat.trials.behavior.mat is never loaded into memory and metrics about behavior is not calculated. Therefore plots using trials as variables (e.g. the default spikes_pos_vs_trials) are not available (see screenshot). Would you be so kind to have this feature supported in the near future?

**Matlab version**
R2021b

**Describe the bug**
Behavioral trials not yet supported

**Matlab error log**

**Session struct**
Peter_MS22_180629_110319_concat.session.mat from example dataset.

**Screenshots**
![Screenshot 2022-11-08 072457](https://user-images.githubusercontent.com/36115995/200606224-cc9bc51b-fbc1-4d9a-b543-5e770a70f4e3.png)

**Additional context**

**Matlab setpath**

**Comment by Jialiang-Lu** [comment]
Thank you for your reply!

Yes the cell_metrics in the example dataset doesn't contain any trail-related info in it. There is `basename.trials.behavior.mat` in the folder containing trial infos, but `ProcessCellMetrics.m` is not loading this file. The lines 

https://github.com/petersenpeter/CellExplorer/blob/c1c1e0fdf91f69e4d87ec380b2de9e224f2ed8fb/ProcessCellMetrics.m#L1267-L1271

seem to be where it should be loaded, but it's empty (correct me if I misunderstood it). When analyzing my own data, I prepared the `.trials.behavior.mat` following the definitions of the data structure. Similarly, this file doesn't seem to be loaded anywhere in the pipeline. Only Neuroscope2 is trying to access it. Could you please explain how to incorporate trial-triggered activity cell_metrics such that CellExplorer can correct plot it?

**Comment by petersenpeter** [comment]
Hi
Please check this tutorial on the subject: https://cellexplorer.org/tutorials/behavior-tutorial/
It is true that it can be improved...

**Comment by petersenpeter** [comment]
You also want to check out the tutorial on raster plots: https://cellexplorer.org/tutorials/plotting-spike-data/
