### ISSUE TITLE
Error using CellExplorer>@(X)X(1:end-2) Too many input arguments.

### ISSUE THREAD

**Issue by JonThom** [petersenpeter/CellExplorer#93]
Error occurs in [getting started](https://cellexplorer.org/#getting-started) section, when running the command `CellExplorer('metrics',cell_metrics)`.

Stack trace: 

> [08-05-2023 09:28:08] Initializing session
> [08-05-2023 09:28:08] Initializing dimensionality reduction plot
> Error using CellExplorer>@(X)X(1:end-2)
> Too many input arguments.
> 
> Error in CellExplorer/initializeSession (line 11267)
>             customPlotOptions = cellfun(@(X) X(1:end-2),customPlotOptions.m,'UniformOutput', false);
> 
> Error in CellExplorer (line 217)
>     initializeSession

Matlab version: R2023a Update 1 (9.14.02239454)

OS: MacOS Monterey 12.5.1, Intel Core i5

**Comment by petersenpeter** [comment]
Hej Jonatan, virker CellExplorer for dig nu?
